"""initial schema

Revision ID: dabf48a0052a
Revises:
Create Date: 2026-07-18 21:06:38.334853
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "dabf48a0052a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_table(
        "notification_preferences",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("reminder_days_before", sa.JSON(), nullable=False),
        sa.Column("push_enabled", sa.Boolean(), nullable=False),
        sa.Column("email_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notification_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_preferences")),
        sa.UniqueConstraint("user_id", name=op.f("uq_notification_preferences_user_id")),
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("vendor_name", sa.String(length=200), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column(
            "item_type",
            sa.Enum("subscription", "bill", "warranty", name="itemtype"),
            nullable=False,
        ),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("previous_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "billing_cycle",
            sa.Enum("weekly", "monthly", "yearly", "one_time", "trial", name="billingcycle"),
            nullable=False,
        ),
        sa.Column("renewal_or_expiry_date", sa.Date(), nullable=True),
        sa.Column(
            "cancellation_difficulty",
            sa.Enum("easy", "moderate", "hard", "unknown", name="cancellationdifficulty"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "canceled", "disputed", name="subscriptionstatus"),
            nullable=False,
        ),
        sa.Column("creature_name", sa.String(length=80), nullable=False),
        sa.Column("creature_species", sa.String(length=40), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_subscriptions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
    )
    op.create_index(
        op.f("ix_subscriptions_archived_at"), "subscriptions", ["archived_at"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_renewal_or_expiry_date"),
        "subscriptions",
        ["renewal_or_expiry_date"],
        unique=False,
    )
    op.create_index(
        "ix_subscriptions_user_date",
        "subscriptions",
        ["user_id", "renewal_or_expiry_date"],
        unique=False,
    )
    op.create_index(op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False)
    op.create_table(
        "widget_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_widget_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_widget_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_widget_tokens_token_hash")),
    )
    op.create_index(op.f("ix_widget_tokens_user_id"), "widget_tokens", ["user_id"], unique=False)
    op.create_table(
        "parsed_receipts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.Uuid(), nullable=True),
        sa.Column("raw_input_type", sa.Enum("text", "image", name="rawinputtype"), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("storage_path", sa.String(length=500), nullable=True),
        sa.Column("extracted_payload", sa.JSON(), nullable=True),
        sa.Column("raw_model_response", sa.JSON(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "completed", "needs_review", "confirmed", name="parsestatus"),
            nullable=False,
        ),
        sa.Column("prompt_version", sa.String(length=80), nullable=False),
        sa.Column("validation_errors", sa.JSON(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_parsed_receipts_subscription_id_subscriptions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_parsed_receipts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parsed_receipts")),
    )
    op.create_index(
        op.f("ix_parsed_receipts_subscription_id"),
        "parsed_receipts",
        ["subscription_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_parsed_receipts_user_id"), "parsed_receipts", ["user_id"], unique=False
    )
    op.create_table(
        "subscription_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "price_hike_detected",
                "resolved_renew",
                "resolved_cancel",
                "resolved_dispute",
                "resolved_keep",
                "reminder_sent",
                name="eventtype",
            ),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_subscription_events_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_events")),
        sa.UniqueConstraint(
            "subscription_id",
            "idempotency_key",
            name=op.f("uq_subscription_events_subscription_id"),
        ),
    )
    op.create_index(
        op.f("ix_subscription_events_occurred_at"),
        "subscription_events",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_events_subscription_id"),
        "subscription_events",
        ["subscription_id"],
        unique=False,
    )
    op.create_index(
        "ix_subscription_events_subscription_time",
        "subscription_events",
        ["subscription_id", "occurred_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_subscription_events_subscription_time", table_name="subscription_events")
    op.drop_index(op.f("ix_subscription_events_subscription_id"), table_name="subscription_events")
    op.drop_index(op.f("ix_subscription_events_occurred_at"), table_name="subscription_events")
    op.drop_table("subscription_events")
    op.drop_index(op.f("ix_parsed_receipts_user_id"), table_name="parsed_receipts")
    op.drop_index(op.f("ix_parsed_receipts_subscription_id"), table_name="parsed_receipts")
    op.drop_table("parsed_receipts")
    op.drop_index(op.f("ix_widget_tokens_user_id"), table_name="widget_tokens")
    op.drop_table("widget_tokens")
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_index("ix_subscriptions_user_date", table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_renewal_or_expiry_date"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_archived_at"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_table("notification_preferences")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
