"""add price intelligence catalog

Revision ID: ece2779ead19
Revises: d1e5f7a9c304
Create Date: 2026-07-20 14:14:23.307355
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "ece2779ead19"
down_revision: Union[str, None] = "d1e5f7a9c304"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

PUBLIC_TABLES = (
    "providers",
    "provider_aliases",
    "source_discovery_runs",
    "source_candidates",
    "discovery_evidence",
    "pricing_sources",
    "provider_plans",
    "source_fetches",
    "deals",
    "plan_alternatives",
    "plan_price_history",
    "user_plan_matches",
    "user_recommendations",
    "price_intelligence_alerts",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "providers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("official_domain", sa.String(length=255), nullable=True),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("logo_url", sa.String(length=1000), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("policy_status", sa.String(length=40), nullable=False),
        sa.Column("last_discovered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_providers")),
        sa.UniqueConstraint("official_domain", name=op.f("uq_providers_official_domain")),
        sa.UniqueConstraint("slug", name=op.f("uq_providers_slug")),
    )
    op.create_index(op.f("ix_providers_active"), "providers", ["active"], unique=False)
    op.create_table(
        "provider_aliases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.String(length=240), nullable=False),
        sa.Column("normalized_alias", sa.String(length=240), nullable=False),
        sa.Column("match_priority", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_provider_aliases_provider_id_providers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_aliases")),
        sa.UniqueConstraint(
            "provider_id", "normalized_alias", name=op.f("uq_provider_aliases_provider_id")
        ),
    )
    op.create_index(
        op.f("ix_provider_aliases_normalized_alias"),
        "provider_aliases",
        ["normalized_alias"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provider_aliases_provider_id"), "provider_aliases", ["provider_id"], unique=False
    )
    op.create_table(
        "source_discovery_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=True),
        sa.Column("run_type", sa.String(length=30), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("query_shard", sa.String(length=120), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("prompt_version", sa.String(length=80), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "running", "completed", "failed", "cost_limited", name="discovery_status"
            ),
            nullable=False,
        ),
        sa.Column("openai_response_id", sa.String(length=200), nullable=True),
        sa.Column("candidate_count", sa.Integer(), nullable=False),
        sa.Column("search_call_count", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_micros", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=100), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_source_discovery_runs_provider_id_providers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_discovery_runs")),
        sa.UniqueConstraint("idempotency_key", name="uq_source_discovery_run_idempotency"),
    )
    op.create_index(
        op.f("ix_source_discovery_runs_provider_id"),
        "source_discovery_runs",
        ["provider_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_discovery_runs_request_id"),
        "source_discovery_runs",
        ["request_id"],
        unique=False,
    )
    op.create_index(
        "ix_source_discovery_runs_status_created",
        "source_discovery_runs",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "source_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("discovery_run_id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=True),
        sa.Column("original_url", sa.String(length=2000), nullable=False),
        sa.Column("normalized_url", sa.String(length=2000), nullable=False),
        sa.Column("normalized_url_hash", sa.String(length=64), nullable=False),
        sa.Column("candidate_domain", sa.String(length=255), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "pricing",
                "plans",
                "promotion",
                "features",
                "help",
                "student",
                "family",
                "annual_discount",
                "regional_pricing",
                "alternatives_evidence",
                name="source_type",
            ),
            nullable=False,
        ),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("language", sa.String(length=12), nullable=False),
        sa.Column("page_title", sa.String(length=500), nullable=True),
        sa.Column("first_party", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("deterministic_score", sa.Float(), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "discovered",
                "validating",
                "verified",
                "active",
                "rejected",
                "needs_review",
                "superseded",
                name="candidate_status",
            ),
            nullable=False,
        ),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_source_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_source_candidates_candidate_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["discovery_run_id"],
            ["source_discovery_runs.id"],
            name=op.f("fk_source_candidates_discovery_run_id_source_discovery_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_source_candidates_provider_id_providers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_candidates")),
        sa.UniqueConstraint(
            "normalized_url_hash",
            "country",
            "source_type",
            name=op.f("uq_source_candidates_normalized_url_hash"),
        ),
    )
    op.create_index(
        op.f("ix_source_candidates_discovery_run_id"),
        "source_candidates",
        ["discovery_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_candidates_normalized_url_hash"),
        "source_candidates",
        ["normalized_url_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_candidates_provider_id"), "source_candidates", ["provider_id"], unique=False
    )
    op.create_index(
        "ix_source_candidates_review", "source_candidates", ["status", "confidence"], unique=False
    )
    op.create_table(
        "discovery_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("evidence_type", sa.String(length=40), nullable=False),
        sa.Column("citation_index", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["source_candidates.id"],
            name=op.f("fk_discovery_evidence_candidate_id_source_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discovery_evidence")),
        sa.UniqueConstraint("candidate_id", "url", name=op.f("uq_discovery_evidence_candidate_id")),
    )
    op.create_index(
        op.f("ix_discovery_evidence_candidate_id"),
        "discovery_evidence",
        ["candidate_id"],
        unique=False,
    )
    op.create_table(
        "pricing_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("discovery_candidate_id", sa.Uuid(), nullable=True),
        sa.Column("canonical_url", sa.String(length=2000), nullable=False),
        sa.Column("normalized_url_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "pricing",
                "plans",
                "promotion",
                "features",
                "help",
                "student",
                "family",
                "annual_discount",
                "regional_pricing",
                "alternatives_evidence",
                name="pricing_source_type",
            ),
            nullable=False,
        ),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("language", sa.String(length=12), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "paused", "failing", "blocked", "superseded", name="source_status"),
            nullable=False,
        ),
        sa.Column("check_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_check_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("etag", sa.String(length=500), nullable=True),
        sa.Column("last_modified", sa.String(length=200), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("semantic_hash", sa.String(length=64), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("lease_token", sa.String(length=100), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_source_id", sa.Uuid(), nullable=True),
        sa.Column("first_discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_rediscovered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("discovery_confidence", sa.Float(), nullable=True),
        sa.Column("prompt_version", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "consecutive_failures >= 0",
            name=op.f("ck_pricing_sources_source_failure_count_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["discovery_candidate_id"],
            ["source_candidates.id"],
            name=op.f("fk_pricing_sources_discovery_candidate_id_source_candidates"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_pricing_sources_provider_id_providers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_source_id"],
            ["pricing_sources.id"],
            name=op.f("fk_pricing_sources_superseded_source_id_pricing_sources"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pricing_sources")),
        sa.UniqueConstraint(
            "normalized_url_hash",
            "country",
            "language",
            name=op.f("uq_pricing_sources_normalized_url_hash"),
        ),
    )
    op.create_index(
        op.f("ix_pricing_sources_discovery_candidate_id"),
        "pricing_sources",
        ["discovery_candidate_id"],
        unique=False,
    )
    op.create_index(
        "ix_pricing_sources_due", "pricing_sources", ["status", "next_check_at"], unique=False
    )
    op.create_index(
        op.f("ix_pricing_sources_lease_expires_at"),
        "pricing_sources",
        ["lease_expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pricing_sources_next_check_at"), "pricing_sources", ["next_check_at"], unique=False
    )
    op.create_index(
        op.f("ix_pricing_sources_normalized_url_hash"),
        "pricing_sources",
        ["normalized_url_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pricing_sources_provider_id"), "pricing_sources", ["provider_id"], unique=False
    )
    op.create_table(
        "provider_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("normalized_name", sa.String(length=300), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "billing_cycle",
            sa.Enum(
                "weekly",
                "monthly",
                "yearly",
                "one_time",
                "trial",
                name="provider_plan_billing_cycle",
            ),
            nullable=False,
        ),
        sa.Column("current_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("monthly_equivalent", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("trial_days", sa.Integer(), nullable=True),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("first_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "current_price >= 0", name=op.f("ck_provider_plans_provider_plan_price_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_provider_plans_provider_id_providers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["pricing_sources.id"],
            name=op.f("fk_provider_plans_source_id_pricing_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_plans")),
        sa.UniqueConstraint(
            "provider_id",
            "external_key",
            "country",
            "currency",
            "billing_cycle",
            name=op.f("uq_provider_plans_provider_id"),
        ),
    )
    op.create_index(op.f("ix_provider_plans_active"), "provider_plans", ["active"], unique=False)
    op.create_index(
        op.f("ix_provider_plans_normalized_name"),
        "provider_plans",
        ["normalized_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provider_plans_provider_id"), "provider_plans", ["provider_id"], unique=False
    )
    op.create_index(
        op.f("ix_provider_plans_source_id"), "provider_plans", ["source_id"], unique=False
    )
    op.create_table(
        "source_fetches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "not_modified",
                "fetched",
                "extracted",
                "failed",
                "rejected",
                name="source_fetch_status",
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("content_type", sa.String(length=200), nullable=True),
        sa.Column("byte_count", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("semantic_hash", sa.String(length=64), nullable=True),
        sa.Column("changed", sa.Boolean(), nullable=False),
        sa.Column("extraction_strategy", sa.String(length=80), nullable=True),
        sa.Column("extraction_version", sa.String(length=80), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("raw_storage_path", sa.String(length=1000), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("sanitized_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["pricing_sources.id"],
            name=op.f("fk_source_fetches_source_id_pricing_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_fetches")),
        sa.UniqueConstraint("source_id", "content_hash", name=op.f("uq_source_fetches_source_id")),
    )
    op.create_index(
        op.f("ix_source_fetches_request_id"), "source_fetches", ["request_id"], unique=False
    )
    op.create_index(
        op.f("ix_source_fetches_source_id"), "source_fetches", ["source_id"], unique=False
    )
    op.create_index(
        "ix_source_fetches_status_created", "source_fetches", ["status", "created_at"], unique=False
    )
    op.create_table(
        "deals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("regular_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("promotional_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("eligibility", sa.JSON(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_url", sa.String(length=2000), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "review_status",
            sa.Enum("pending", "approved", "rejected", "auto_approved", name="deal_review_status"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["provider_plans.id"],
            name=op.f("fk_deals_plan_id_provider_plans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_deals_provider_id_providers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["pricing_sources.id"],
            name=op.f("fk_deals_source_id_pricing_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deals")),
        sa.UniqueConstraint(
            "provider_id", "source_id", "fingerprint", name=op.f("uq_deals_provider_id")
        ),
    )
    op.create_index("ix_deals_active_expiry", "deals", ["active", "expires_at"], unique=False)
    op.create_index(op.f("ix_deals_expires_at"), "deals", ["expires_at"], unique=False)
    op.create_index(op.f("ix_deals_plan_id"), "deals", ["plan_id"], unique=False)
    op.create_index(op.f("ix_deals_provider_id"), "deals", ["provider_id"], unique=False)
    op.create_table(
        "plan_alternatives",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_plan_id", sa.Uuid(), nullable=False),
        sa.Column("alternative_plan_id", sa.Uuid(), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("feature_similarity", sa.Float(), nullable=False),
        sa.Column("monthly_savings", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("annual_savings", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("switching_effort", sa.Integer(), nullable=False),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["alternative_plan_id"],
            ["provider_plans.id"],
            name=op.f("fk_plan_alternatives_alternative_plan_id_provider_plans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_plan_id"],
            ["provider_plans.id"],
            name=op.f("fk_plan_alternatives_source_plan_id_provider_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_alternatives")),
        sa.UniqueConstraint(
            "source_plan_id",
            "alternative_plan_id",
            "country",
            name=op.f("uq_plan_alternatives_source_plan_id"),
        ),
    )
    op.create_index(
        op.f("ix_plan_alternatives_alternative_plan_id"),
        "plan_alternatives",
        ["alternative_plan_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_plan_alternatives_source_plan_id"),
        "plan_alternatives",
        ["source_plan_id"],
        unique=False,
    )
    op.create_table(
        "plan_price_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("source_fetch_id", sa.Uuid(), nullable=True),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("promotional_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("previous_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("change_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("change_percentage", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column(
            "change_type",
            sa.Enum("initial", "increase", "decrease", "unchanged", name="price_change_type"),
            nullable=False,
        ),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "review_status",
            sa.Enum("pending", "approved", "rejected", "auto_approved", name="price_review_status"),
            nullable=False,
        ),
        sa.Column("evidence_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "price >= 0", name=op.f("ck_plan_price_history_price_history_price_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["provider_plans.id"],
            name=op.f("fk_plan_price_history_plan_id_provider_plans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_fetch_id"],
            ["source_fetches.id"],
            name=op.f("fk_plan_price_history_source_fetch_id_source_fetches"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_price_history")),
        sa.UniqueConstraint("plan_id", "evidence_hash", name=op.f("uq_plan_price_history_plan_id")),
    )
    op.create_index(
        op.f("ix_plan_price_history_plan_id"), "plan_price_history", ["plan_id"], unique=False
    )
    op.create_index(
        "ix_plan_price_history_plan_observed",
        "plan_price_history",
        ["plan_id", "observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_plan_price_history_source_fetch_id"),
        "plan_price_history",
        ["source_fetch_id"],
        unique=False,
    )
    op.create_table(
        "user_plan_matches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("provider_plan_id", sa.Uuid(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("method", sa.String(length=40), nullable=False),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "confirmed", "rejected", "unmatched", name="match_status"),
            nullable=False,
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_user_plan_matches_match_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_user_plan_matches_provider_id_providers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_plan_id"],
            ["provider_plans.id"],
            name=op.f("fk_user_plan_matches_provider_plan_id_provider_plans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_user_plan_matches_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_plan_matches_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_plan_matches")),
        sa.UniqueConstraint(
            "subscription_id", "provider_plan_id", name=op.f("uq_user_plan_matches_subscription_id")
        ),
    )
    op.create_index(
        op.f("ix_user_plan_matches_subscription_id"),
        "user_plan_matches",
        ["subscription_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_plan_matches_user_id"), "user_plan_matches", ["user_id"], unique=False
    )
    op.create_table(
        "user_recommendations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("recommendation_type", sa.String(length=60), nullable=False),
        sa.Column("target_plan_id", sa.Uuid(), nullable=True),
        sa.Column("deal_id", sa.Uuid(), nullable=True),
        sa.Column("deduplication_key", sa.String(length=200), nullable=False),
        sa.Column("estimated_monthly_savings", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("estimated_annual_savings", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("generator_version", sa.String(length=80), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active", "seen", "dismissed", "accepted", "expired", name="recommendation_status"
            ),
            nullable=False,
        ),
        sa.Column("seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("feedback", sa.String(length=40), nullable=True),
        sa.Column("feedback_reason", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["deals.id"],
            name=op.f("fk_user_recommendations_deal_id_deals"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_user_recommendations_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_plan_id"],
            ["provider_plans.id"],
            name=op.f("fk_user_recommendations_target_plan_id_provider_plans"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_recommendations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_recommendations")),
        sa.UniqueConstraint(
            "user_id",
            "subscription_id",
            "deduplication_key",
            name=op.f("uq_user_recommendations_user_id"),
        ),
    )
    op.create_index(
        "ix_user_recommendations_active",
        "user_recommendations",
        ["user_id", "status", "expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_recommendations_subscription_id"),
        "user_recommendations",
        ["subscription_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_recommendations_user_id"), "user_recommendations", ["user_id"], unique=False
    )
    op.create_table(
        "price_intelligence_alerts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("recommendation_id", sa.Uuid(), nullable=True),
        sa.Column("price_history_id", sa.Uuid(), nullable=True),
        sa.Column("deal_id", sa.Uuid(), nullable=True),
        sa.Column("alert_type", sa.String(length=60), nullable=False),
        sa.Column("deduplication_key", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "delivered", "failed", "read", name="price_alert_delivery_status"),
            nullable=False,
        ),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("request_id", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["deals.id"],
            name=op.f("fk_price_intelligence_alerts_deal_id_deals"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["price_history_id"],
            ["plan_price_history.id"],
            name=op.f("fk_price_intelligence_alerts_price_history_id_plan_price_history"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["user_recommendations.id"],
            name=op.f("fk_price_intelligence_alerts_recommendation_id_user_recommendations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_price_intelligence_alerts_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_price_intelligence_alerts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_intelligence_alerts")),
        sa.UniqueConstraint(
            "user_id", "deduplication_key", name=op.f("uq_price_intelligence_alerts_user_id")
        ),
    )
    op.create_index(
        "ix_price_alerts_delivery",
        "price_intelligence_alerts",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_intelligence_alerts_request_id"),
        "price_intelligence_alerts",
        ["request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_intelligence_alerts_subscription_id"),
        "price_intelligence_alerts",
        ["subscription_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_intelligence_alerts_user_id"),
        "price_intelligence_alerts",
        ["user_id"],
        unique=False,
    )
    if op.get_bind().dialect.name == "postgresql":
        for table in PUBLIC_TABLES:
            op.execute(f'ALTER TABLE public."{table}" ENABLE ROW LEVEL SECURITY')
            for role in ("anon", "authenticated"):
                op.execute(
                    f"""DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{role}') THEN
                        EXECUTE 'REVOKE ALL ON TABLE public."{table}" FROM {role}';
                    END IF;
                    END $$"""
                )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        for table in reversed(PUBLIC_TABLES):
            op.execute(f'ALTER TABLE public."{table}" DISABLE ROW LEVEL SECURITY')
    op.drop_index(
        op.f("ix_price_intelligence_alerts_user_id"), table_name="price_intelligence_alerts"
    )
    op.drop_index(
        op.f("ix_price_intelligence_alerts_subscription_id"), table_name="price_intelligence_alerts"
    )
    op.drop_index(
        op.f("ix_price_intelligence_alerts_request_id"), table_name="price_intelligence_alerts"
    )
    op.drop_index("ix_price_alerts_delivery", table_name="price_intelligence_alerts")
    op.drop_table("price_intelligence_alerts")
    op.drop_index(op.f("ix_user_recommendations_user_id"), table_name="user_recommendations")
    op.drop_index(
        op.f("ix_user_recommendations_subscription_id"), table_name="user_recommendations"
    )
    op.drop_index("ix_user_recommendations_active", table_name="user_recommendations")
    op.drop_table("user_recommendations")
    op.drop_index(op.f("ix_user_plan_matches_user_id"), table_name="user_plan_matches")
    op.drop_index(op.f("ix_user_plan_matches_subscription_id"), table_name="user_plan_matches")
    op.drop_table("user_plan_matches")
    op.drop_index(op.f("ix_plan_price_history_source_fetch_id"), table_name="plan_price_history")
    op.drop_index("ix_plan_price_history_plan_observed", table_name="plan_price_history")
    op.drop_index(op.f("ix_plan_price_history_plan_id"), table_name="plan_price_history")
    op.drop_table("plan_price_history")
    op.drop_index(op.f("ix_plan_alternatives_source_plan_id"), table_name="plan_alternatives")
    op.drop_index(op.f("ix_plan_alternatives_alternative_plan_id"), table_name="plan_alternatives")
    op.drop_table("plan_alternatives")
    op.drop_index(op.f("ix_deals_provider_id"), table_name="deals")
    op.drop_index(op.f("ix_deals_plan_id"), table_name="deals")
    op.drop_index(op.f("ix_deals_expires_at"), table_name="deals")
    op.drop_index("ix_deals_active_expiry", table_name="deals")
    op.drop_table("deals")
    op.drop_index("ix_source_fetches_status_created", table_name="source_fetches")
    op.drop_index(op.f("ix_source_fetches_source_id"), table_name="source_fetches")
    op.drop_index(op.f("ix_source_fetches_request_id"), table_name="source_fetches")
    op.drop_table("source_fetches")
    op.drop_index(op.f("ix_provider_plans_source_id"), table_name="provider_plans")
    op.drop_index(op.f("ix_provider_plans_provider_id"), table_name="provider_plans")
    op.drop_index(op.f("ix_provider_plans_normalized_name"), table_name="provider_plans")
    op.drop_index(op.f("ix_provider_plans_active"), table_name="provider_plans")
    op.drop_table("provider_plans")
    op.drop_index(op.f("ix_pricing_sources_provider_id"), table_name="pricing_sources")
    op.drop_index(op.f("ix_pricing_sources_normalized_url_hash"), table_name="pricing_sources")
    op.drop_index(op.f("ix_pricing_sources_next_check_at"), table_name="pricing_sources")
    op.drop_index(op.f("ix_pricing_sources_lease_expires_at"), table_name="pricing_sources")
    op.drop_index("ix_pricing_sources_due", table_name="pricing_sources")
    op.drop_index(op.f("ix_pricing_sources_discovery_candidate_id"), table_name="pricing_sources")
    op.drop_table("pricing_sources")
    op.drop_index(op.f("ix_discovery_evidence_candidate_id"), table_name="discovery_evidence")
    op.drop_table("discovery_evidence")
    op.drop_index("ix_source_candidates_review", table_name="source_candidates")
    op.drop_index(op.f("ix_source_candidates_provider_id"), table_name="source_candidates")
    op.drop_index(op.f("ix_source_candidates_normalized_url_hash"), table_name="source_candidates")
    op.drop_index(op.f("ix_source_candidates_discovery_run_id"), table_name="source_candidates")
    op.drop_table("source_candidates")
    op.drop_index("ix_source_discovery_runs_status_created", table_name="source_discovery_runs")
    op.drop_index(op.f("ix_source_discovery_runs_request_id"), table_name="source_discovery_runs")
    op.drop_index(op.f("ix_source_discovery_runs_provider_id"), table_name="source_discovery_runs")
    op.drop_table("source_discovery_runs")
    op.drop_index(op.f("ix_provider_aliases_provider_id"), table_name="provider_aliases")
    op.drop_index(op.f("ix_provider_aliases_normalized_alias"), table_name="provider_aliases")
    op.drop_table("provider_aliases")
    op.drop_index(op.f("ix_providers_active"), table_name="providers")
    op.drop_table("providers")
    # ### end Alembic commands ###
